#!/bin/bash

## Command aliases.
# Colorize ls
alias ls='ls --color=always'
# Colorize less
alias less='less -R'
# Colorize grep (light green)
export GREP_COLORS="1,32"
# Emacs terminal
alias em='emacs -nw -Q'
# Emacs X
alias emx='emacs -Q -ib 5'

# Remap caps to ctrl.
setxkbmap -option ctrl:nocaps

# brakes terminal tab title --- RETHINK ---
#Prompt Setup.
# `root` has a red prompt, others a light green one.
# If we are connected remotely, `@<hostname>` shows first.

build_ps1() {
    local prompt_color='\[\e[32m\]'
    local host=''
    [[ $UID -eq 0 ]] && prompt_color='\[\e[1;31m\]'
    [[ $SSH_TTY ]] && host="@$HOSTNAME "
    echo "${prompt_color}${host}\w\[\e[0m\] \$ "
}

# IF terminal exixts add title
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\] $(build_ps1)"
    ;;
*)
    PS1=$(build_ps1)
    ;;
esac

PS2='\\ '
PS4='+ $LINENO: '  
