#!/bin/bash

# Copy files to ~/
cp bash_aliases ~/.bash_aliases
cp emacs ~/.emacs
cp gitignore_global ~/.gitignore_global

# Setup git
read -p "Enter GIT global username : " username
read -p "Enter GIT global email    : " email
printf "Using $username/$email\n"

git config --global core.excludesfile ~/.gitignore_global
git config --global user.name "$username"
git config --global user.email "$email"
git config --global core.editor em
