#!/bin/bash

## copy files to ~/
cp bashrc_add ~/.bashrc_add
cp emacs ~/.emacs
cp gitignore_global ~/.gitignore_global

## setup git
git config --global core.excludesfile ~/.gitignore_global
git config --global user.name "kNottien"
git config --global user.email "kentarveolsen@gmail.com"
git config --global core.editor em

## add script to .bashrc
printf "\n## kNottien config\n. .bashrc_add\n" >> ~/.bashrc
